import {
  Organization,
  Project,
  Task,
  TeamMember,
  AgentActivity,
  KpiCard,
  TimeByPartyData,
  ApprovalTimeData,
  CommentRoundsData,
  Permit,
} from "./types";

// Organization
export const mockOrganization: Organization = {
  id: "org-1",
  name: "Airavata Engineering",
  slug: "airavata-engineering",
};

// Team Members
export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Sarah Martinez",
    email: "sarah.martinez@airavata.com",
    role: "Project Manager",
    avatar: null,
    initials: "SM",
  },
  {
    id: "tm-2",
    name: "James Chen",
    email: "james.chen@airavata.com",
    role: "Permit Coordinator",
    avatar: null,
    initials: "JC",
  },
  {
    id: "tm-3",
    name: "Michael Rodriguez",
    email: "michael.rodriguez@airavata.com",
    role: "Structural Engineer",
    avatar: null,
    initials: "MR",
  },
  {
    id: "tm-4",
    name: "Emily Thompson",
    email: "emily.thompson@airavata.com",
    role: "Architect",
    avatar: null,
    initials: "ET",
  },
  {
    id: "tm-5",
    name: "David Patel",
    email: "david.patel@airavata.com",
    role: "Admin",
    avatar: null,
    initials: "DP",
  },
  {
    id: "tm-6",
    name: "Lisa Garcia",
    email: "lisa.garcia@airavata.com",
    role: "Field Inspector",
    avatar: null,
    initials: "LG",
  },
];

// Projects with realistic South Florida data
export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Brickell Luxury Condo Tower",
    address: "1200 Brickell Avenue",
    city: "Miami",
    state: "FL",
    zipCode: "33131",
    jurisdiction: "Miami",
    status: "approved",
    permitType: "building",
    assignee: mockTeamMembers[0],
    contractor: "Turner Construction",
    architect: "Arquitectonica",
    createdAt: "2025-11-15",
    updatedAt: "2026-03-28",
    submittedAt: "2025-12-10",
    approvedAt: "2026-03-15",
    estimatedApproval: "2026-03-10",
    commentRounds: 2,
    totalTasks: 8,
    completedTasks: 8,
    value: 1850000,
  },
  {
    id: "proj-2",
    name: "Wynwood Arts District Mixed-Use",
    address: "2820 NW 2nd Avenue",
    city: "Miami",
    state: "FL",
    zipCode: "33127",
    jurisdiction: "Miami",
    status: "in_review",
    permitType: "building",
    assignee: mockTeamMembers[1],
    contractor: "Coastal Builders",
    architect: "Perkins and Will",
    createdAt: "2025-10-22",
    updatedAt: "2026-03-29",
    submittedAt: "2026-01-18",
    approvedAt: null,
    estimatedApproval: "2026-04-15",
    commentRounds: 1,
    totalTasks: 12,
    completedTasks: 10,
    value: 650000,
  },
  {
    id: "proj-3",
    name: "Fort Lauderdale Beach Residential",
    address: "550 Fort Lauderdale Beach Boulevard",
    city: "Fort Lauderdale",
    state: "FL",
    zipCode: "33316",
    jurisdiction: "Fort Lauderdale",
    status: "revision",
    permitType: "building",
    assignee: mockTeamMembers[2],
    contractor: "Bergman Development",
    architect: "Duany Plater-Zyberk & Co.",
    createdAt: "2025-09-05",
    updatedAt: "2026-03-27",
    submittedAt: "2026-01-10",
    approvedAt: null,
    estimatedApproval: "2026-05-01",
    commentRounds: 3,
    totalTasks: 15,
    completedTasks: 11,
    value: 2100000,
  },
  {
    id: "proj-4",
    name: "Coral Gables Historic Renovation",
    address: "1001 Coral Way",
    city: "Coral Gables",
    state: "FL",
    zipCode: "33134",
    jurisdiction: "Coral Gables",
    status: "issued",
    permitType: "roofing",
    assignee: mockTeamMembers[3],
    contractor: "Heritage Restoration Inc.",
    architect: "Morris Architects",
    createdAt: "2025-08-10",
    updatedAt: "2026-03-20",
    submittedAt: "2025-11-05",
    approvedAt: "2026-02-28",
    estimatedApproval: "2026-02-15",
    commentRounds: 1,
    totalTasks: 6,
    completedTasks: 6,
    value: 450000,
  },
  {
    id: "proj-5",
    name: "Hialeah Industrial Complex",
    address: "8500 NW 74th Street",
    city: "Hialeah",
    state: "FL",
    zipCode: "33166",
    jurisdiction: "Hialeah",
    status: "in_review",
    permitType: "electrical",
    assignee: mockTeamMembers[1],
    contractor: "Industrial Builders Group",
    architect: "TL Architects",
    createdAt: "2025-07-18",
    updatedAt: "2026-03-26",
    submittedAt: "2026-02-14",
    approvedAt: null,
    estimatedApproval: "2026-04-20",
    commentRounds: 2,
    totalTasks: 10,
    completedTasks: 8,
    value: 890000,
  },
  {
    id: "proj-6",
    name: "Pembroke Pines Shopping Center",
    address: "14201 Pines Boulevard",
    city: "Pembroke Pines",
    state: "FL",
    zipCode: "33027",
    jurisdiction: "Pembroke Pines",
    status: "intake",
    permitType: "mechanical",
    assignee: mockTeamMembers[4],
    contractor: "Retail Development Corp",
    architect: "Stantec Architecture",
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
    submittedAt: null,
    approvedAt: null,
    estimatedApproval: null,
    commentRounds: 0,
    totalTasks: 4,
    completedTasks: 1,
    value: 1200000,
  },
  {
    id: "proj-7",
    name: "Hollywood Oceanfront Condo",
    address: "3000 Ocean Drive",
    city: "Hollywood",
    state: "FL",
    zipCode: "33019",
    jurisdiction: "Hollywood",
    status: "approved",
    permitType: "building",
    assignee: mockTeamMembers[0],
    contractor: "Coastal High-Rise Builders",
    architect: "Arquitectonica",
    createdAt: "2025-12-01",
    updatedAt: "2026-03-22",
    submittedAt: "2026-01-25",
    approvedAt: "2026-03-18",
    estimatedApproval: "2026-03-10",
    commentRounds: 1,
    totalTasks: 9,
    completedTasks: 9,
    value: 1550000,
  },
  {
    id: "proj-8",
    name: "Doral Office Park Expansion",
    address: "9395 NW 41st Street",
    city: "Doral",
    state: "FL",
    zipCode: "33178",
    jurisdiction: "Doral",
    status: "revision",
    permitType: "building",
    assignee: mockTeamMembers[2],
    contractor: "Office Park Developers",
    architect: "Gensler",
    createdAt: "2025-10-05",
    updatedAt: "2026-03-25",
    submittedAt: "2026-02-03",
    approvedAt: null,
    estimatedApproval: "2026-05-15",
    commentRounds: 2,
    totalTasks: 11,
    completedTasks: 8,
    value: 1100000,
  },
  {
    id: "proj-9",
    name: "Aventura Mall Renovation",
    address: "19501 Biscayne Boulevard",
    city: "Aventura",
    state: "FL",
    zipCode: "33180",
    jurisdiction: "Aventura",
    status: "in_review",
    permitType: "mechanical",
    assignee: mockTeamMembers[3],
    contractor: "Major Malls Inc.",
    architect: "DPZ & Company",
    createdAt: "2025-11-20",
    updatedAt: "2026-03-29",
    submittedAt: "2026-02-20",
    approvedAt: null,
    estimatedApproval: "2026-04-10",
    commentRounds: 2,
    totalTasks: 13,
    completedTasks: 11,
    value: 800000,
  },
  {
    id: "proj-10",
    name: "Palmetto Commercial Hub",
    address: "9801 Palmetto Commerce Parkway",
    city: "Palmetto",
    state: "FL",
    zipCode: "33157",
    jurisdiction: "Palmetto",
    status: "issued",
    permitType: "plumbing",
    assignee: mockTeamMembers[1],
    contractor: "Commercial Builders United",
    architect: "Perkins Eastman",
    createdAt: "2025-09-12",
    updatedAt: "2026-03-15",
    submittedAt: "2025-12-28",
    approvedAt: "2026-03-01",
    estimatedApproval: "2026-02-28",
    commentRounds: 1,
    totalTasks: 7,
    completedTasks: 7,
    value: 520000,
  },
  {
    id: "proj-11",
    name: "Miami Beach Rooftop Garden",
    address: "1111 Lincoln Road",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33139",
    jurisdiction: "Miami Beach",
    status: "on_hold",
    permitType: "roofing",
    assignee: mockTeamMembers[5],
    contractor: "Urban Green Builders",
    architect: "Kengo Kuma & Associates",
    createdAt: "2025-08-28",
    updatedAt: "2026-03-10",
    submittedAt: "2026-01-15",
    approvedAt: null,
    estimatedApproval: null,
    commentRounds: 2,
    totalTasks: 8,
    completedTasks: 5,
    value: 380000,
  },
  {
    id: "proj-12",
    name: "Pinecrest Medical Center",
    address: "12600 South Dixie Highway",
    city: "Pinecrest",
    state: "FL",
    zipCode: "33156",
    jurisdiction: "Pinecrest",
    status: "approved",
    permitType: "electrical",
    assignee: mockTeamMembers[2],
    contractor: "Healthcare Facilities Group",
    architect: "Cannon Design",
    createdAt: "2025-10-30",
    updatedAt: "2026-03-23",
    submittedAt: "2026-02-08",
    approvedAt: "2026-03-20",
    estimatedApproval: "2026-03-15",
    commentRounds: 1,
    totalTasks: 9,
    completedTasks: 9,
    value: 950000,
  },
  {
    id: "proj-13",
    name: "Tamiami Park Demolition",
    address: "3000 SW 8th Street",
    city: "Miami",
    state: "FL",
    zipCode: "33135",
    jurisdiction: "Miami",
    status: "issued",
    permitType: "demolition",
    assignee: mockTeamMembers[0],
    contractor: "Demolition Experts LLC",
    architect: "N/A",
    createdAt: "2025-09-01",
    updatedAt: "2026-03-18",
    submittedAt: "2025-11-20",
    approvedAt: "2026-02-15",
    estimatedApproval: "2026-02-10",
    commentRounds: 0,
    totalTasks: 5,
    completedTasks: 5,
    value: 280000,
  },
  {
    id: "proj-14",
    name: "Buena Vista Apartments HVAC",
    address: "4545 NE 2nd Avenue",
    city: "Miami",
    state: "FL",
    zipCode: "33137",
    jurisdiction: "Miami",
    status: "revision",
    permitType: "mechanical",
    assignee: mockTeamMembers[3],
    contractor: "HVAC Solutions Corp",
    architect: "Nichols Architects",
    createdAt: "2025-11-08",
    updatedAt: "2026-03-28",
    submittedAt: "2026-02-25",
    approvedAt: null,
    estimatedApproval: "2026-05-05",
    commentRounds: 2,
    totalTasks: 10,
    completedTasks: 7,
    value: 625000,
  },
  {
    id: "proj-15",
    name: "Allapattah Community Center",
    address: "2401 NW 7th Street",
    city: "Miami",
    state: "FL",
    zipCode: "33125",
    jurisdiction: "Miami",
    status: "in_review",
    permitType: "building",
    assignee: mockTeamMembers[1],
    contractor: "Community Development Inc.",
    architect: "HOK (Hellmuth, Obata & Kassabaum)",
    createdAt: "2025-12-10",
    updatedAt: "2026-03-27",
    submittedAt: "2026-03-05",
    approvedAt: null,
    estimatedApproval: "2026-04-25",
    commentRounds: 1,
    totalTasks: 11,
    completedTasks: 9,
    value: 1400000,
  },
  {
    id: "proj-16",
    name: "Westchester Fire Alarm System",
    address: "8100 SW 24th Street",
    city: "Miami",
    state: "FL",
    zipCode: "33155",
    jurisdiction: "Miami",
    status: "approved",
    permitType: "fire_alarm",
    assignee: mockTeamMembers[4],
    contractor: "Fire Safety Systems",
    architect: "N/A",
    createdAt: "2025-10-15",
    updatedAt: "2026-03-21",
    submittedAt: "2026-02-12",
    approvedAt: "2026-03-19",
    estimatedApproval: "2026-03-15",
    commentRounds: 0,
    totalTasks: 6,
    completedTasks: 6,
    value: 185000,
  },
  {
    id: "proj-17",
    name: "Brickell Sign Installation",
    address: "1300 Brickell Avenue",
    city: "Miami",
    state: "FL",
    zipCode: "33131",
    jurisdiction: "Miami",
    status: "intake",
    permitType: "sign",
    assignee: mockTeamMembers[5],
    contractor: "Signage Innovations",
    architect: "N/A",
    createdAt: "2026-03-25",
    updatedAt: "2026-03-25",
    submittedAt: null,
    approvedAt: null,
    estimatedApproval: null,
    commentRounds: 0,
    totalTasks: 3,
    completedTasks: 0,
    value: 95000,
  },
];

// Tasks with realistic data matching the dashboard
export const mockTasks: Task[] = [
  {
    id: "task-1",
    projectId: "proj-3",
    projectName: "Fort Lauderdale Beach Residential",
    title: "Collect spec sheets",
    description: "Obtain MEP equipment specification sheets from contractor",
    status: "overdue",
    priority: "high",
    assignee: mockTeamMembers[1],
    dueDate: "2026-03-20",
    createdAt: "2026-03-10",
  },
  {
    id: "task-2",
    projectId: "proj-8",
    projectName: "Doral Office Park Expansion",
    title: "Mechanical engineer license verification",
    description: "Verify PE license is current and in good standing",
    status: "overdue",
    priority: "urgent",
    assignee: mockTeamMembers[2],
    dueDate: "2026-03-22",
    createdAt: "2026-03-12",
  },
  {
    id: "task-3",
    projectId: "proj-14",
    projectName: "Buena Vista Apartments HVAC",
    title: "Customer contract signature",
    description: "Obtain signed customer agreement for HVAC work",
    status: "in_progress",
    priority: "high",
    assignee: mockTeamMembers[0],
    dueDate: "2026-04-02",
    createdAt: "2026-03-15",
  },
  {
    id: "task-4",
    projectId: "proj-2",
    projectName: "Wynwood Arts District Mixed-Use",
    title: "Homeowner signature on COI",
    description: "Get homeowner to sign Certificate of Insurance",
    status: "pending",
    priority: "medium",
    assignee: mockTeamMembers[3],
    dueDate: "2026-04-05",
    createdAt: "2026-03-18",
  },
  {
    id: "task-5",
    projectId: "proj-5",
    projectName: "Hialeah Industrial Complex",
    title: "Certificate of Insurance submission",
    description: "Submit COI to jurisdiction AHJ",
    status: "pending",
    priority: "high",
    assignee: mockTeamMembers[1],
    dueDate: "2026-04-08",
    createdAt: "2026-03-16",
  },
  {
    id: "task-6",
    projectId: "proj-9",
    projectName: "Aventura Mall Renovation",
    title: "Architectural drawings revision",
    description: "Address AHJ comments on floor plans and elevations",
    status: "in_progress",
    priority: "high",
    assignee: mockTeamMembers[3],
    dueDate: "2026-04-10",
    createdAt: "2026-03-20",
  },
  {
    id: "task-7",
    projectId: "proj-6",
    projectName: "Pembroke Pines Shopping Center",
    title: "Project intake meeting",
    description: "Initial meeting with contractor and architect",
    status: "completed",
    priority: "medium",
    assignee: mockTeamMembers[4],
    dueDate: "2026-03-29",
    createdAt: "2026-03-21",
  },
  {
    id: "task-8",
    projectId: "proj-12",
    projectName: "Pinecrest Medical Center",
    title: "Final permit pickup confirmation",
    description: "Confirm permit has been picked up by contractor",
    status: "completed",
    priority: "medium",
    assignee: mockTeamMembers[2],
    dueDate: "2026-03-25",
    createdAt: "2026-03-20",
  },
  {
    id: "task-9",
    projectId: "proj-7",
    projectName: "Hollywood Oceanfront Condo",
    title: "Building permit punchlist items",
    description: "Address final minor items before approval",
    status: "completed",
    priority: "low",
    assignee: mockTeamMembers[0],
    dueDate: "2026-03-18",
    createdAt: "2026-03-10",
  },
  {
    id: "task-10",
    projectId: "proj-11",
    projectName: "Miami Beach Rooftop Garden",
    title: "Structural calculation review",
    description: "PE review of rooftop loading calculations",
    status: "blocked",
    priority: "high",
    assignee: mockTeamMembers[2],
    dueDate: "2026-04-01",
    createdAt: "2026-03-05",
  },
];

// Agent Activities
export const mockAgentActivities: AgentActivity[] = [
  {
    id: "activity-1",
    type: "research",
    title: "5 projects researched",
    description: "Requirements gathered",
    status: "completed",
    projectCount: 5,
    progress: 100,
  },
  {
    id: "activity-2",
    type: "revision",
    title: "3 projects revised",
    description: "Comments analyzed",
    status: "completed",
    projectCount: 3,
    progress: 100,
  },
  {
    id: "activity-3",
    type: "submission",
    title: "Submitting 4 projects",
    description: "Sending to AHJ...",
    status: "in_progress",
    projectCount: 4,
    progress: 65,
  },
  {
    id: "activity-4",
    type: "preparation",
    title: "2 applications in preparation",
    description: "Auto-filling forms...",
    status: "in_progress",
    projectCount: 2,
    progress: 42,
  },
  {
    id: "activity-5",
    type: "analysis",
    title: "Building code analysis",
    description: "Reviewing wind speed and flood zone requirements",
    status: "queued",
    projectCount: 8,
    progress: 0,
  },
];

// KPI Cards matching the dashboard
export const mockKpiCards: KpiCard[] = [
  {
    title: "Projects Submitted",
    value: 119,
    change: 14,
    changeLabel: "+14% from last month",
    trend: "up",
  },
  {
    title: "Projects in AHJ Review",
    value: 15,
    change: -12,
    changeLabel: "-12% from last month",
    trend: "down",
  },
  {
    title: "Projects in Revision",
    value: 16,
    change: -25,
    changeLabel: "-25% from last month",
    trend: "down",
  },
  {
    title: "Permits Issued",
    value: 84,
    change: 37,
    changeLabel: "+37% from last month",
    trend: "up",
  },
];

// Time by Party Chart Data (12 months)
export const mockTimeByPartyData: TimeByPartyData[] = [
  {
    month: "Apr",
    contractor: 320,
    subcontractor: 180,
    architect: 150,
    owner: 90,
    ahj: 140,
  },
  {
    month: "May",
    contractor: 380,
    subcontractor: 210,
    architect: 170,
    owner: 110,
    ahj: 160,
  },
  {
    month: "Jun",
    contractor: 340,
    subcontractor: 190,
    architect: 155,
    owner: 95,
    ahj: 150,
  },
  {
    month: "Jul",
    contractor: 410,
    subcontractor: 240,
    architect: 185,
    owner: 120,
    ahj: 175,
  },
  {
    month: "Aug",
    contractor: 390,
    subcontractor: 220,
    architect: 175,
    owner: 105,
    ahj: 165,
  },
  {
    month: "Sep",
    contractor: 350,
    subcontractor: 200,
    architect: 160,
    owner: 100,
    ahj: 155,
  },
  {
    month: "Oct",
    contractor: 420,
    subcontractor: 250,
    architect: 190,
    owner: 125,
    ahj: 180,
  },
  {
    month: "Nov",
    contractor: 380,
    subcontractor: 215,
    architect: 170,
    owner: 110,
    ahj: 160,
  },
  {
    month: "Dec",
    contractor: 340,
    subcontractor: 190,
    architect: 155,
    owner: 95,
    ahj: 150,
  },
  {
    month: "Jan",
    contractor: 360,
    subcontractor: 205,
    architect: 165,
    owner: 105,
    ahj: 155,
  },
  {
    month: "Feb",
    contractor: 390,
    subcontractor: 220,
    architect: 175,
    owner: 115,
    ahj: 165,
  },
  {
    month: "Mar",
    contractor: 410,
    subcontractor: 235,
    architect: 185,
    owner: 120,
    ahj: 175,
  },
];

// Approval Time Chart Data (12 months)
export const mockApprovalTimeData: ApprovalTimeData[] = [
  { month: "Apr", days: 28 },
  { month: "May", days: 32 },
  { month: "Jun", days: 25 },
  { month: "Jul", days: 35 },
  { month: "Aug", days: 30 },
  { month: "Sep", days: 27 },
  { month: "Oct", days: 38 },
  { month: "Nov", days: 33 },
  { month: "Dec", days: 26 },
  { month: "Jan", days: 29 },
  { month: "Feb", days: 31 },
  { month: "Mar", days: 34 },
];

// Comment Rounds Chart Data (12 months)
export const mockCommentRoundsData: CommentRoundsData[] = [
  { month: "Apr", rounds: 1.8 },
  { month: "May", rounds: 2.1 },
  { month: "Jun", rounds: 1.5 },
  { month: "Jul", rounds: 2.4 },
  { month: "Aug", rounds: 2.0 },
  { month: "Sep", rounds: 1.7 },
  { month: "Oct", rounds: 2.3 },
  { month: "Nov", rounds: 2.0 },
  { month: "Dec", rounds: 1.6 },
  { month: "Jan", rounds: 1.9 },
  { month: "Feb", rounds: 2.1 },
  { month: "Mar", rounds: 2.2 },
];

// Permits
export const mockPermits: Permit[] = [
  {
    id: "perm-1",
    projectId: "proj-1",
    type: "building",
    number: "2026-001847",
    status: "issued",
    submittedAt: "2025-12-10",
    issuedAt: "2026-03-15",
    expiresAt: "2029-03-15",
    fees: 12500,
  },
  {
    id: "perm-2",
    projectId: "proj-4",
    type: "roofing",
    number: "2026-001345",
    status: "issued",
    submittedAt: "2025-11-05",
    issuedAt: "2026-02-28",
    expiresAt: "2028-02-28",
    fees: 3500,
  },
  {
    id: "perm-3",
    projectId: "proj-7",
    type: "building",
    number: "2026-001756",
    status: "approved",
    submittedAt: "2026-01-25",
    issuedAt: null,
    expiresAt: null,
    fees: 9800,
  },
  {
    id: "perm-4",
    projectId: "proj-10",
    type: "plumbing",
    number: "2026-001234",
    status: "issued",
    submittedAt: "2025-12-28",
    issuedAt: "2026-03-01",
    expiresAt: "2028-03-01",
    fees: 2800,
  },
  {
    id: "perm-5",
    projectId: "proj-12",
    type: "electrical",
    number: "2026-001845",
    status: "approved",
    submittedAt: "2026-02-08",
    issuedAt: null,
    expiresAt: null,
    fees: 6500,
  },
  {
    id: "perm-6",
    projectId: "proj-13",
    type: "demolition",
    number: "2026-001023",
    status: "issued",
    submittedAt: "2025-11-20",
    issuedAt: "2026-02-15",
    expiresAt: "2027-02-15",
    fees: 1800,
  },
  {
    id: "perm-7",
    projectId: "proj-16",
    type: "fire_alarm",
    number: "2026-001556",
    status: "approved",
    submittedAt: "2026-02-12",
    issuedAt: null,
    expiresAt: null,
    fees: 1200,
  },
];

// Export all mock data as a collection
export const mockData = {
  organization: mockOrganization,
  teamMembers: mockTeamMembers,
  projects: mockProjects,
  tasks: mockTasks,
  agentActivities: mockAgentActivities,
  kpiCards: mockKpiCards,
  timeByPartyData: mockTimeByPartyData,
  approvalTimeData: mockApprovalTimeData,
  commentRoundsData: mockCommentRoundsData,
  permits: mockPermits,
};
